// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.GameIndice
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.Version
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class GameIndiceJsonAdapter(
  moshi: Moshi
) : JsonAdapter<GameIndice>() {
  private val options: JsonReader.Options = JsonReader.Options.of("game_index", "version")

  private val nullableIntAdapter: JsonAdapter<Int?> = moshi.adapter(Int::class.javaObjectType,
      emptySet(), "gameIndex")

  private val nullableVersionAdapter: JsonAdapter<Version?> = moshi.adapter(Version::class.java,
      emptySet(), "version")

  @Volatile
  private var constructorRef: Constructor<GameIndice>? = null

  public override fun toString(): String = buildString(32) {
      append("GeneratedJsonAdapter(").append("GameIndice").append(')') }

  public override fun fromJson(reader: JsonReader): GameIndice {
    var gameIndex: Int? = null
    var version: Version? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          gameIndex = nullableIntAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          version = nullableVersionAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  GameIndice(
          gameIndex = gameIndex,
          version = version
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<GameIndice> = this.constructorRef ?:
          GameIndice::class.java.getDeclaredConstructor(Int::class.javaObjectType,
          Version::class.java, Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          gameIndex,
          version,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: GameIndice?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("game_index")
    nullableIntAdapter.toJson(writer, value_.gameIndex)
    writer.name("version")
    nullableVersionAdapter.toJson(writer, value_.version)
    writer.endObject()
  }
}
