// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.GenerationViii
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.IconsX
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class GenerationViiiJsonAdapter(
  moshi: Moshi
) : JsonAdapter<GenerationViii>() {
  private val options: JsonReader.Options = JsonReader.Options.of("icons")

  private val nullableIconsXAdapter: JsonAdapter<IconsX?> = moshi.adapter(IconsX::class.java,
      emptySet(), "icons")

  @Volatile
  private var constructorRef: Constructor<GenerationViii>? = null

  public override fun toString(): String = buildString(36) {
      append("GeneratedJsonAdapter(").append("GenerationViii").append(')') }

  public override fun fromJson(reader: JsonReader): GenerationViii {
    var icons: IconsX? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          icons = nullableIconsXAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffe.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  GenerationViii(
          icons = icons
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<GenerationViii> = this.constructorRef ?:
          GenerationViii::class.java.getDeclaredConstructor(IconsX::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          icons,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: GenerationViii?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("icons")
    nullableIconsXAdapter.toJson(writer, value_.icons)
    writer.endObject()
  }
}
