// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.HeldItem
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.Item
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.VersionDetail
import com.squareup.moshi.*
import com.squareup.moshi.internal.Util
import java.lang.reflect.Constructor
import kotlin.Int

public class HeldItemJsonAdapter(
  moshi: Moshi
) : JsonAdapter<HeldItem>() {
  private val options: JsonReader.Options = JsonReader.Options.of("item", "versionDetails")

  private val nullableItemAdapter: JsonAdapter<Item?> = moshi.adapter(Item::class.java, emptySet(),
      "item")

  private val nullableListOfVersionDetailAdapter: JsonAdapter<List<VersionDetail>?> =
      moshi.adapter(Types.newParameterizedType(List::class.java, VersionDetail::class.java),
      emptySet(), "versionDetails")

  @Volatile
  private var constructorRef: Constructor<HeldItem>? = null

  public override fun toString(): String = buildString(30) {
      append("GeneratedJsonAdapter(").append("HeldItem").append(')') }

  public override fun fromJson(reader: JsonReader): HeldItem {
    var item: Item? = null
    var versionDetails: List<VersionDetail>? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          item = nullableItemAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          versionDetails = nullableListOfVersionDetailAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  HeldItem(
          item = item,
          versionDetails = versionDetails
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<HeldItem> = this.constructorRef ?:
          HeldItem::class.java.getDeclaredConstructor(Item::class.java, List::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          item,
          versionDetails,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: HeldItem?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("item")
    nullableItemAdapter.toJson(writer, value_.item)
    writer.name("versionDetails")
    nullableListOfVersionDetailAdapter.toJson(writer, value_.versionDetails)
    writer.endObject()
  }
}
