// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.Move
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.MoveX
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.VersionGroupDetail
import com.squareup.moshi.*
import com.squareup.moshi.internal.Util
import java.lang.reflect.Constructor
import kotlin.Int

public class MoveJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Move>() {
  private val options: JsonReader.Options = JsonReader.Options.of("move", "version_group_details")

  private val nullableMoveXAdapter: JsonAdapter<MoveX?> = moshi.adapter(MoveX::class.java,
      emptySet(), "move")

  private val nullableListOfVersionGroupDetailAdapter: JsonAdapter<List<VersionGroupDetail>?> =
      moshi.adapter(Types.newParameterizedType(List::class.java, VersionGroupDetail::class.java),
      emptySet(), "versionGroupDetails")

  @Volatile
  private var constructorRef: Constructor<Move>? = null

  public override fun toString(): String = buildString(26) {
      append("GeneratedJsonAdapter(").append("Move").append(')') }

  public override fun fromJson(reader: JsonReader): Move {
    var move: MoveX? = null
    var versionGroupDetails: List<VersionGroupDetail>? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          move = nullableMoveXAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          versionGroupDetails = nullableListOfVersionGroupDetailAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  Move(
          move = move,
          versionGroupDetails = versionGroupDetails
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<Move> = this.constructorRef ?:
          Move::class.java.getDeclaredConstructor(MoveX::class.java, List::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          move,
          versionGroupDetails,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: Move?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("move")
    nullableMoveXAdapter.toJson(writer, value_.move)
    writer.name("version_group_details")
    nullableListOfVersionGroupDetailAdapter.toJson(writer, value_.versionGroupDetails)
    writer.endObject()
  }
}
