// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.Stat
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.StatX
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class StatJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Stat>() {
  private val options: JsonReader.Options = JsonReader.Options.of("base_stat", "effort", "stat")

  private val nullableIntAdapter: JsonAdapter<Int?> = moshi.adapter(Int::class.javaObjectType,
      emptySet(), "baseStat")

  private val nullableStatXAdapter: JsonAdapter<StatX?> = moshi.adapter(StatX::class.java,
      emptySet(), "stat")

  @Volatile
  private var constructorRef: Constructor<Stat>? = null

  public override fun toString(): String = buildString(26) {
      append("GeneratedJsonAdapter(").append("Stat").append(')') }

  public override fun fromJson(reader: JsonReader): Stat {
    var baseStat: Int? = null
    var effort: Int? = null
    var stat: StatX? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          baseStat = nullableIntAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          effort = nullableIntAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> {
          stat = nullableStatXAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 2).inv()
          mask0 = mask0 and 0xfffffffb.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffff8.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  Stat(
          baseStat = baseStat,
          effort = effort,
          stat = stat
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<Stat> = this.constructorRef ?:
          Stat::class.java.getDeclaredConstructor(Int::class.javaObjectType,
          Int::class.javaObjectType, StatX::class.java, Int::class.javaPrimitiveType,
          Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
      return localConstructor.newInstance(
          baseStat,
          effort,
          stat,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: Stat?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("base_stat")
    nullableIntAdapter.toJson(writer, value_.baseStat)
    writer.name("effort")
    nullableIntAdapter.toJson(writer, value_.effort)
    writer.name("stat")
    nullableStatXAdapter.toJson(writer, value_.stat)
    writer.endObject()
  }
}
