// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.Type
import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.TypeX
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.internal.Util
import java.lang.reflect.Constructor
import kotlin.Int

public class TypeJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Type>() {
  private val options: JsonReader.Options = JsonReader.Options.of("slot", "type")

  private val nullableIntAdapter: JsonAdapter<Int?> = moshi.adapter(Int::class.javaObjectType,
      emptySet(), "slot")

  private val nullableTypeXAdapter: JsonAdapter<TypeX?> = moshi.adapter(TypeX::class.java,
      emptySet(), "type")

  @Volatile
  private var constructorRef: Constructor<Type>? = null

  public override fun toString(): String = buildString(26) {
      append("GeneratedJsonAdapter(").append("Type").append(')') }

  public override fun fromJson(reader: JsonReader): Type {
    var slot: Int? = null
    var type: TypeX? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          slot = nullableIntAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          type = nullableTypeXAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  Type(
          slot = slot,
          type = type
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<Type> = this.constructorRef ?:
          Type::class.java.getDeclaredConstructor(Int::class.javaObjectType, TypeX::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          slot,
          type,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: Type?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("slot")
    nullableIntAdapter.toJson(writer, value_.slot)
    writer.name("type")
    nullableTypeXAdapter.toJson(writer, value_.type)
    writer.endObject()
  }
}
