// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.pokemon

import com.kobeissidev.jetpackcomposepokedex.data.model.pokemon.*
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.internal.Util
import java.lang.reflect.Constructor
import kotlin.Int

public class VersionsJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Versions>() {
  private val options: JsonReader.Options = JsonReader.Options.of("generation-i", "generation-ii",
      "generation-iii", "generation-iv", "generation-v", "generation-vi", "generation-vii",
      "generation-viii")

  private val nullableGenerationIAdapter: JsonAdapter<GenerationI?> =
      moshi.adapter(GenerationI::class.java, emptySet(), "generationI")

  private val nullableGenerationIiAdapter: JsonAdapter<GenerationIi?> =
      moshi.adapter(GenerationIi::class.java, emptySet(), "generationII")

  private val nullableGenerationIiiAdapter: JsonAdapter<GenerationIii?> =
      moshi.adapter(GenerationIii::class.java, emptySet(), "generationIII")

  private val nullableGenerationIvAdapter: JsonAdapter<GenerationIv?> =
      moshi.adapter(GenerationIv::class.java, emptySet(), "generationIV")

  private val nullableGenerationVAdapter: JsonAdapter<GenerationV?> =
      moshi.adapter(GenerationV::class.java, emptySet(), "generationV")

  private val nullableGenerationViAdapter: JsonAdapter<GenerationVi?> =
      moshi.adapter(GenerationVi::class.java, emptySet(), "generationVI")

  private val nullableGenerationViiAdapter: JsonAdapter<GenerationVii?> =
      moshi.adapter(GenerationVii::class.java, emptySet(), "generationVII")

  private val nullableGenerationViiiAdapter: JsonAdapter<GenerationViii?> =
      moshi.adapter(GenerationViii::class.java, emptySet(), "generationVIII")

  @Volatile
  private var constructorRef: Constructor<Versions>? = null

  public override fun toString(): String = buildString(30) {
      append("GeneratedJsonAdapter(").append("Versions").append(')') }

  public override fun fromJson(reader: JsonReader): Versions {
    var generationI: GenerationI? = null
    var generationII: GenerationIi? = null
    var generationIII: GenerationIii? = null
    var generationIV: GenerationIv? = null
    var generationV: GenerationV? = null
    var generationVI: GenerationVi? = null
    var generationVII: GenerationVii? = null
    var generationVIII: GenerationViii? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          generationI = nullableGenerationIAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          generationII = nullableGenerationIiAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> {
          generationIII = nullableGenerationIiiAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 2).inv()
          mask0 = mask0 and 0xfffffffb.toInt()
        }
        3 -> {
          generationIV = nullableGenerationIvAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 3).inv()
          mask0 = mask0 and 0xfffffff7.toInt()
        }
        4 -> {
          generationV = nullableGenerationVAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 4).inv()
          mask0 = mask0 and 0xffffffef.toInt()
        }
        5 -> {
          generationVI = nullableGenerationViAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 5).inv()
          mask0 = mask0 and 0xffffffdf.toInt()
        }
        6 -> {
          generationVII = nullableGenerationViiAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 6).inv()
          mask0 = mask0 and 0xffffffbf.toInt()
        }
        7 -> {
          generationVIII = nullableGenerationViiiAdapter.fromJson(reader)
          // $mask = $mask and (1 shl 7).inv()
          mask0 = mask0 and 0xffffff7f.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xffffff00.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  Versions(
          generationI = generationI,
          generationII = generationII,
          generationIII = generationIII,
          generationIV = generationIV,
          generationV = generationV,
          generationVI = generationVI,
          generationVII = generationVII,
          generationVIII = generationVIII
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<Versions> = this.constructorRef ?:
          Versions::class.java.getDeclaredConstructor(GenerationI::class.java,
          GenerationIi::class.java, GenerationIii::class.java, GenerationIv::class.java,
          GenerationV::class.java, GenerationVi::class.java, GenerationVii::class.java,
          GenerationViii::class.java, Int::class.javaPrimitiveType,
          Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
      return localConstructor.newInstance(
          generationI,
          generationII,
          generationIII,
          generationIV,
          generationV,
          generationVI,
          generationVII,
          generationVIII,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: Versions?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("generation-i")
    nullableGenerationIAdapter.toJson(writer, value_.generationI)
    writer.name("generation-ii")
    nullableGenerationIiAdapter.toJson(writer, value_.generationII)
    writer.name("generation-iii")
    nullableGenerationIiiAdapter.toJson(writer, value_.generationIII)
    writer.name("generation-iv")
    nullableGenerationIvAdapter.toJson(writer, value_.generationIV)
    writer.name("generation-v")
    nullableGenerationVAdapter.toJson(writer, value_.generationV)
    writer.name("generation-vi")
    nullableGenerationViAdapter.toJson(writer, value_.generationVI)
    writer.name("generation-vii")
    nullableGenerationViiAdapter.toJson(writer, value_.generationVII)
    writer.name("generation-viii")
    nullableGenerationViiiAdapter.toJson(writer, value_.generationVIII)
    writer.endObject()
  }
}
