// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.move

import com.kobeissidev.jetpackcomposepokedex.data.model.move.ContestCombos
import com.kobeissidev.jetpackcomposepokedex.data.model.move.Normal
import com.kobeissidev.jetpackcomposepokedex.data.model.move.Super
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class ContestCombosJsonAdapter(
  moshi: Moshi
) : JsonAdapter<ContestCombos>() {
  private val options: JsonReader.Options = JsonReader.Options.of("normal", "super")

  private val normalAdapter: JsonAdapter<Normal> = moshi.adapter(Normal::class.java, emptySet(),
      "normal")

  private val superAdapter: JsonAdapter<Super> = moshi.adapter(Super::class.java, emptySet(),
      "superX")

  @Volatile
  private var constructorRef: Constructor<ContestCombos>? = null

  public override fun toString(): String = buildString(35) {
      append("GeneratedJsonAdapter(").append("ContestCombos").append(')') }

  public override fun fromJson(reader: JsonReader): ContestCombos {
    var normal: Normal? = null
    var superX: Super? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          normal = normalAdapter.fromJson(reader) ?: throw Util.unexpectedNull("normal", "normal",
              reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          superX = superAdapter.fromJson(reader) ?: throw Util.unexpectedNull("superX", "super",
              reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  ContestCombos(
          normal = normal as Normal,
          superX = superX as Super
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<ContestCombos> = this.constructorRef ?:
          ContestCombos::class.java.getDeclaredConstructor(Normal::class.java, Super::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          normal,
          superX,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: ContestCombos?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("normal")
    normalAdapter.toJson(writer, value_.normal)
    writer.name("super")
    superAdapter.toJson(writer, value_.superX)
    writer.endObject()
  }
}
