// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.move

import com.kobeissidev.jetpackcomposepokedex.data.model.move.EffectEntry
import com.kobeissidev.jetpackcomposepokedex.data.model.move.Language
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.internal.Util
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String

public class EffectEntryJsonAdapter(
  moshi: Moshi
) : JsonAdapter<EffectEntry>() {
  private val options: JsonReader.Options = JsonReader.Options.of("effect", "language",
      "short_effect")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "effect")

  private val languageAdapter: JsonAdapter<Language> = moshi.adapter(Language::class.java,
      emptySet(), "language")

  @Volatile
  private var constructorRef: Constructor<EffectEntry>? = null

  public override fun toString(): String = buildString(33) {
      append("GeneratedJsonAdapter(").append("EffectEntry").append(')') }

  public override fun fromJson(reader: JsonReader): EffectEntry {
    var effect: String? = null
    var language: Language? = null
    var shortEffect: String? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          effect = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("effect", "effect",
              reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          language = languageAdapter.fromJson(reader) ?: throw Util.unexpectedNull("language",
              "language", reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> {
          shortEffect = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("shortEffect",
              "short_effect", reader)
          // $mask = $mask and (1 shl 2).inv()
          mask0 = mask0 and 0xfffffffb.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffff8.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  EffectEntry(
          effect = effect as String,
          language = language as Language,
          shortEffect = shortEffect as String
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<EffectEntry> = this.constructorRef ?:
          EffectEntry::class.java.getDeclaredConstructor(String::class.java, Language::class.java,
          String::class.java, Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          effect,
          language,
          shortEffect,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: EffectEntry?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("effect")
    stringAdapter.toJson(writer, value_.effect)
    writer.name("language")
    languageAdapter.toJson(writer, value_.language)
    writer.name("short_effect")
    stringAdapter.toJson(writer, value_.shortEffect)
    writer.endObject()
  }
}
