// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.remotekey

import com.kobeissidev.jetpackcomposepokedex.data.model.remotekey.RemoteKey
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.text.buildString

public class RemoteKeyJsonAdapter(
  moshi: Moshi
) : JsonAdapter<RemoteKey>() {
  private val options: JsonReader.Options = JsonReader.Options.of("id", "prevKey", "nextKey")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "id")

  private val nullableIntAdapter: JsonAdapter<Int?> = moshi.adapter(Int::class.javaObjectType,
      emptySet(), "prevKey")

  public override fun toString(): String = buildString(31) {
      append("GeneratedJsonAdapter(").append("RemoteKey").append(')') }

  public override fun fromJson(reader: JsonReader): RemoteKey {
    var id: String? = null
    var prevKey: Int? = null
    var nextKey: Int? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> id = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("id", "id", reader)
        1 -> prevKey = nullableIntAdapter.fromJson(reader)
        2 -> nextKey = nullableIntAdapter.fromJson(reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    return RemoteKey(
        id = id ?: throw Util.missingProperty("id", "id", reader),
        prevKey = prevKey,
        nextKey = nextKey
    )
  }

  public override fun toJson(writer: JsonWriter, value_: RemoteKey?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("id")
    stringAdapter.toJson(writer, value_.id)
    writer.name("prevKey")
    nullableIntAdapter.toJson(writer, value_.prevKey)
    writer.name("nextKey")
    nullableIntAdapter.toJson(writer, value_.nextKey)
    writer.endObject()
  }
}
