// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.species

import com.kobeissidev.jetpackcomposepokedex.data.model.species.FlavorTextEntry
import com.kobeissidev.jetpackcomposepokedex.data.model.species.Language
import com.kobeissidev.jetpackcomposepokedex.data.model.species.Version
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class FlavorTextEntryJsonAdapter(
  moshi: Moshi
) : JsonAdapter<FlavorTextEntry>() {
  private val options: JsonReader.Options = JsonReader.Options.of("flavor_text", "language",
      "version")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "flavorText")

  private val languageAdapter: JsonAdapter<Language> = moshi.adapter(Language::class.java,
      emptySet(), "language")

  private val versionAdapter: JsonAdapter<Version> = moshi.adapter(Version::class.java, emptySet(),
      "version")

  @Volatile
  private var constructorRef: Constructor<FlavorTextEntry>? = null

  public override fun toString(): String = buildString(37) {
      append("GeneratedJsonAdapter(").append("FlavorTextEntry").append(')') }

  public override fun fromJson(reader: JsonReader): FlavorTextEntry {
    var flavorText: String? = null
    var language: Language? = null
    var version: Version? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          flavorText = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("flavorText",
              "flavor_text", reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          language = languageAdapter.fromJson(reader) ?: throw Util.unexpectedNull("language",
              "language", reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        2 -> {
          version = versionAdapter.fromJson(reader) ?: throw Util.unexpectedNull("version",
              "version", reader)
          // $mask = $mask and (1 shl 2).inv()
          mask0 = mask0 and 0xfffffffb.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffff8.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  FlavorTextEntry(
          flavorText = flavorText as String,
          language = language as Language,
          version = version as Version
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<FlavorTextEntry> = this.constructorRef ?:
          FlavorTextEntry::class.java.getDeclaredConstructor(String::class.java,
          Language::class.java, Version::class.java, Int::class.javaPrimitiveType,
          Util.DEFAULT_CONSTRUCTOR_MARKER).also { this.constructorRef = it }
      return localConstructor.newInstance(
          flavorText,
          language,
          version,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: FlavorTextEntry?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("flavor_text")
    stringAdapter.toJson(writer, value_.flavorText)
    writer.name("language")
    languageAdapter.toJson(writer, value_.language)
    writer.name("version")
    versionAdapter.toJson(writer, value_.version)
    writer.endObject()
  }
}
