// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.species

import com.kobeissidev.jetpackcomposepokedex.data.model.species.Genera
import com.kobeissidev.jetpackcomposepokedex.data.model.species.LanguageX
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class GeneraJsonAdapter(
  moshi: Moshi
) : JsonAdapter<Genera>() {
  private val options: JsonReader.Options = JsonReader.Options.of("genus", "language")

  private val stringAdapter: JsonAdapter<String> = moshi.adapter(String::class.java, emptySet(),
      "genus")

  private val languageXAdapter: JsonAdapter<LanguageX> = moshi.adapter(LanguageX::class.java,
      emptySet(), "language")

  @Volatile
  private var constructorRef: Constructor<Genera>? = null

  public override fun toString(): String = buildString(28) {
      append("GeneratedJsonAdapter(").append("Genera").append(')') }

  public override fun fromJson(reader: JsonReader): Genera {
    var genus: String? = null
    var language: LanguageX? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          genus = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("genus", "genus",
              reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          language = languageXAdapter.fromJson(reader) ?: throw Util.unexpectedNull("language",
              "language", reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  Genera(
          genus = genus as String,
          language = language as LanguageX
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<Genera> = this.constructorRef ?:
          Genera::class.java.getDeclaredConstructor(String::class.java, LanguageX::class.java,
          Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          genus,
          language,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: Genera?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("genus")
    stringAdapter.toJson(writer, value_.genus)
    writer.name("language")
    languageXAdapter.toJson(writer, value_.language)
    writer.endObject()
  }
}
