// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.kobeissidev.jetpackcomposepokedex.data.local.converters.species

import com.kobeissidev.jetpackcomposepokedex.data.model.species.Pokedex
import com.kobeissidev.jetpackcomposepokedex.data.model.species.PokedexNumber
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import java.lang.reflect.Constructor
import kotlin.Int
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.jvm.Volatile
import kotlin.text.buildString

public class PokedexNumberJsonAdapter(
  moshi: Moshi
) : JsonAdapter<PokedexNumber>() {
  private val options: JsonReader.Options = JsonReader.Options.of("entry_number", "pokedex")

  private val intAdapter: JsonAdapter<Int> = moshi.adapter(Int::class.java, emptySet(),
      "entryNumber")

  private val pokedexAdapter: JsonAdapter<Pokedex> = moshi.adapter(Pokedex::class.java, emptySet(),
      "pokedex")

  @Volatile
  private var constructorRef: Constructor<PokedexNumber>? = null

  public override fun toString(): String = buildString(35) {
      append("GeneratedJsonAdapter(").append("PokedexNumber").append(')') }

  public override fun fromJson(reader: JsonReader): PokedexNumber {
    var entryNumber: Int? = 0
    var pokedex: Pokedex? = null
    var mask0 = -1
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> {
          entryNumber = intAdapter.fromJson(reader) ?: throw Util.unexpectedNull("entryNumber",
              "entry_number", reader)
          // $mask = $mask and (1 shl 0).inv()
          mask0 = mask0 and 0xfffffffe.toInt()
        }
        1 -> {
          pokedex = pokedexAdapter.fromJson(reader) ?: throw Util.unexpectedNull("pokedex",
              "pokedex", reader)
          // $mask = $mask and (1 shl 1).inv()
          mask0 = mask0 and 0xfffffffd.toInt()
        }
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    if (mask0 == 0xfffffffc.toInt()) {
      // All parameters with defaults are set, invoke the constructor directly
      return  PokedexNumber(
          entryNumber = entryNumber as Int,
          pokedex = pokedex as Pokedex
      )
    } else {
      // Reflectively invoke the synthetic defaults constructor
      @Suppress("UNCHECKED_CAST")
      val localConstructor: Constructor<PokedexNumber> = this.constructorRef ?:
          PokedexNumber::class.java.getDeclaredConstructor(Int::class.javaPrimitiveType,
          Pokedex::class.java, Int::class.javaPrimitiveType, Util.DEFAULT_CONSTRUCTOR_MARKER).also {
          this.constructorRef = it }
      return localConstructor.newInstance(
          entryNumber,
          pokedex,
          mask0,
          /* DefaultConstructorMarker */ null
      )
    }
  }

  public override fun toJson(writer: JsonWriter, value_: PokedexNumber?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("entry_number")
    intAdapter.toJson(writer, value_.entryNumber)
    writer.name("pokedex")
    pokedexAdapter.toJson(writer, value_.pokedex)
    writer.endObject()
  }
}
